# Generated by Django 4.1.2 on 2024-06-17 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APremiun',
            fields=[
                ('id_apremiun', models.AutoField(db_column='idAPremiun', primary_key=True, serialize=False)),
                ('nombre_apremiun', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id_asiento', models.AutoField(db_column='idAsiento', primary_key=True, serialize=False)),
                ('nombre_asiento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(db_column='idAsistencia', primary_key=True, serialize=False)),
                ('nombre_asistencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id_discapacidad', models.AutoField(db_column='idDiscapacidad', primary_key=True, serialize=False)),
                ('nombre_discapacidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EAdicional',
            fields=[
                ('id_eadicional', models.AutoField(db_column='idEAdicional', primary_key=True, serialize=False)),
                ('nombre_eadicional', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HPremiun',
            fields=[
                ('id_hpremiun', models.AutoField(db_column='idHPremiun', primary_key=True, serialize=False)),
                ('nombre_hpremiun', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(db_column='idMascota', primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id_seguro', models.AutoField(db_column='idSeguro', primary_key=True, serialize=False)),
                ('nombre_seguro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=9)),
                ('emergencia', models.CharField(max_length=9)),
                ('servicio_adicional', models.CharField(max_length=255)),
                ('id_apremiun', models.ForeignKey(db_column='idAPremiun', on_delete=django.db.models.deletion.CASCADE, to='ParaViajar.apremiun')),
                ('id_asiento', models.ForeignKey(db_column='idAsiento', on_delete=django.db.models.deletion.CASCADE, to='ParaViajar.asiento')),
                ('id_asistencia', models.ForeignKey(db_column='idAsistencia', on_delete=django.db.models.deletion.CASCADE, to='ParaViajar.asistencia')),
                ('id_discapacidad', models.ForeignKey(db_column='idDiscapacidad', on_delete=django.db.models.deletion.CASCADE, to='ParaViajar.discapacidad')),
                ('id_eadicional', models.ForeignKey(db_column='idEAdicional', on_delete=django.db.models.deletion.CASCADE, to='ParaViajar.eadicional')),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='ParaViajar.genero')),
                ('id_hpremiun', models.ForeignKey(db_column='idHPremiun', on_delete=django.db.models.deletion.CASCADE, to='ParaViajar.hpremiun')),
                ('id_mascota', models.ForeignKey(db_column='idMascota', on_delete=django.db.models.deletion.CASCADE, to='ParaViajar.mascota')),
                ('id_seguro', models.ForeignKey(db_column='idSeguro', on_delete=django.db.models.deletion.CASCADE, to='ParaViajar.seguro')),
            ],
        ),
    ]
